### ISSUE TITLE
panic when calculating the aabb of the convex hull of a relatively complex geometry

### ISSUE THREAD

**Issue by arturoc** [sebcrozet/ncollide#193]
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.6.3/bounding_volume/aabb_utils.rs:35:34
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
   9: ncollide_geometry::bounding_volume::aabb_utils::point_cloud_aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.6.3/bounding_volume/aabb_utils.rs:35
  10: ncollide_geometry::bounding_volume::aabb::aabb
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.6.3/bounding_volume/aabb_convex.rs:9
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.6.3/bounding_volume/aabb.rs:17
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_geometry-0.6.3/shape/shape_impl.rs:39
             at src/system_types/src/editor.rs:172
             at /checkout/src/libcore/ops/function.rs:271
  12: <alloc::vec::Vec<T>>::extend_desugared
             at /checkout/src/libcore/option.rs:404
             at /checkout/src/libcore/iter/mod.rs:1347
             at /checkout/src/liballoc/vec.rs:1956
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1853
             at /checkout/src/liballoc/vec.rs:1848
  14: system_types::editor::add_editor_collisions
             at /checkout/src/liballoc/vec.rs:1748
             at /checkout/src/libcore/iter/iterator.rs:1373
             at src/system_types/src/editor.rs:157
  15: system_types::editor::Editor::new
             at src/system_types/src/editor.rs:241
```

**Comment by arturoc** [comment]
Sorry this was happening on an empty geometry
