### ISSUE TITLE
Division by Zero panic

### ISSUE THREAD

**Issue by Futile** [sebcrozet/ncollide#98]
I got the following panic while using ncollide:

```
thread '<main>' panicked at 'attempted remainder with a divisor of zero', /home/felix/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/ncollide_pipeline-0.2.3/broad_phase/dbvt_broad_phase.rs:251
stack backtrace:
   1:     0x5626d744e38e - sys::backtrace::write::h9d7a90b82951696dZws
   2:     0x5626d74517d6 - panicking::on_panic::h84e509cf0bec31052lx
   3:     0x5626d744623e - rt::unwind::begin_unwind_inner::h2e32ca1bf051967dF1w
   4:     0x5626d74467f6 - rt::unwind::begin_unwind_fmt::h323f20488ad2d748L0w
   5:     0x5626d74511a6 - rust_begin_unwind
   6:     0x5626d7480784 - panicking::panic_fmt::h4ce2c934001461b3PgC
   7:     0x5626d747d39d - panicking::panic::ha99d8a0f519968ebmfC
   8:     0x5626d71bc616 - broad_phase::dbvt_broad_phase::DBVTBroadPhase<P, BV, T>.BroadPhase<P, BV, T>::update::h16299623997403973611
                        at /home/felix/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/ncollide_pipeline-0.2.3/broad_phase/dbvt_broad_phase.rs:251
   9:     0x5626d7189b49 - world::collision_world::CollisionWorld<P, M, T>::perform_broad_phase::h6981986958437046442
                        at /home/felix/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/ncollide_pipeline-0.2.3/world/collision_world.rs:132
  10:     0x5626d7188da2 - world::collision_world::CollisionWorld<P, M, T>::update::h2304234016377033558
                        at /home/felix/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/ncollide_pipeline-0.2.3/world/collision_world.rs:87
```

The error line in pipeline/dbvt_broad_phase.rs is here: https://github.com/sebcrozet/ncollide/blob/master/ncollide_pipeline/broad_phase/dbvt_broad_phase.rs#L251

It seems that the last contact pair was removed, and thus the `% self.pairs.len()` results in a division by zero.

**Comment by Futile** [comment]
I pushed a fix to https://github.com/sebcrozet/ncollide/pull/99, which resets `self.update_off` to 0 in case no more pairs are present.
